branches:
  # PRs are always built. So we exclude branch builds other than master to prevent double-builds.
  # https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
  only:
    - master

# Job queue; see below for default job settings.
jobs:
  include:
    - name: "lib"
      language: node_js
      script:
        - ./ci/build-npm-package.sh lib
    - name: "ui"
      language: node_js
      script:
        - ./ci/build-npm-package.sh ui

dist: bionic
group: travis_latest
os: linux
node_js: ["14"]
